spring:
  application:
    name: video-workflow
  profiles:
    active: prod

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}

server:
  port: ${SERVER_PORT:8080}

app:
  upload:
    bucket: ${VIDEO_BUCKET}
    key-prefix: video-uploads/

aws:
  region: ${AWS_REGION:us-east-1}

  s3:
    endpoint: ${AWS_S3_ENDPOINT:}
    path-style-access: ${AWS_S3_PATH_STYLE_ACCESS:false}

  sns:
    topic-arn: ${AWS_SNS_TOPIC_ARN}

  sqs:
    status-queue-url: ${AWS_SQS_STATUS_QUEUE_URL}

springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED:true}
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:true}