name: CI / CD - video-workflow - Destroy

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type the word "destroy" to confirm destructive action'
        required: true
        default: ''

concurrency:
  group: video-workflow-destroy
  cancel-in-progress: false

jobs:
  terraform-destroy:
    name: Terraform Destroy (manual)
    runs-on: ubuntu-latest
    environment: production
    if: github.event.inputs.confirm == 'destroy'
    defaults:
      run:
        working-directory: terraform

    steps:
      - uses: actions/checkout@v5

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.13"

      - name: Confirm intent
        run: echo "Destructive action confirmed."

      - uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-region: ${{ vars.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}

      - name: Terraform Init (reconfigure backend)
        run: terraform init -input=false -reconfigure

      - name: Terraform Destroy Plan
        run: |
          terraform plan -destroy -out=tfplan -input=false -lock-timeout=300s \
            -var region="${{ vars.AWS_REGION }}" \
            -var eks_cluster_name="${{ vars.EKS_CLUSTER_NAME }}" \
            -var app_image="public.ecr.aws/${{ vars.ECR_PUBLIC_ALIAS }}/video-workflow:latest" \
            -var db_user="${{ secrets.DB_USER }}" \
            -var db_password="${{ secrets.DB_PASSWORD }}" \
            -var spring_datasource_url="${{ vars.SPRING_DATASOURCE_URL }}" \
            -var video_bucket="${{ vars.VIDEO_BUCKET }}" \
            -var aws_sqs_status_queue_url="${{ vars.AWS_SQS_STATUS_QUEUE_URL }}" \
            -var sns_topic_arn="${{ vars.SNS_TOPIC_ARN }}" \
            -var aws_s3_endpoint="${{ vars.AWS_S3_ENDPOINT }}" \
            -var aws_s3_path_style_access="${{ vars.AWS_S3_PATH_STYLE_ACCESS }}"

      - name: Terraform Destroy Apply
        run: terraform apply -auto-approve tfplan


  skip-warning:
    name: Skip warning
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm != 'destroy'
    steps:
      - run: |
          echo "You must type 'destroy' to run this workflow."
          exit 1